//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigmaERP.hrms.personnel {
    
    
    public partial class employee_activity_tracking {
        
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        
        protected global::System.Web.UI.WebControls.Literal litMessage;
        
        protected global::System.Web.UI.WebControls.TextBox txtEmployee;
        
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        
        protected global::System.Web.UI.WebControls.TextBox txtFromTime;
        
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        
        protected global::System.Web.UI.WebControls.TextBox txtToTime;
        
        protected global::System.Web.UI.WebControls.Button btnSearch;
        
        protected global::System.Web.UI.WebControls.Literal litEmployeeName;
        
        protected global::System.Web.UI.WebControls.Literal litTotalPoints;
        
        protected global::System.Web.UI.WebControls.Literal litFirstSeen;
        
        protected global::System.Web.UI.WebControls.Literal litLastSeen;
        
        protected global::System.Web.UI.WebControls.GridView gvActivity;
    }
}
